export const environment = {
  production: false, 
  DomainURL: "https://crm.thontrang.com/",  
  DomainDestination: "https://crm.thontrang.com/#/",  
  APIURL: "https://api.thontrang.com/",    
  LoginURL: "https://login.thontrang.com/",
  Website: "https://thontrang.com/",
  Images: "images",  
  Download: "Download",  
  LoadingFile: "loading.gif",
  DialogConfigWidth: "80%",
  InitializationString: "",  
  InitializationNumber: 0, 
  CompanyIDThonTrang: 1, 
  CompanyIDBiBen: 2, 
  CompanyIDVyTam: 3, 
  AuthenticationToken: "AuthenticationToken",
  MembershipID: "MembershipID",  
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.", 
  SaveSuccess: "Lưu thành công.",
  SaveNotSuccess: "Lưu không thành công.",  
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",      
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",    
  LoginNotSuccess: "Đăng nhập không thành công.",        
};

