export class Product {
    ID?: number;   
    UserCreated?: number;    
    DateCreated?: Date;    
    UserUpdated?: number;    
    DateUpdated?: Date;    
    ParentID?: number;    
    Note?: string;    
    Active?: boolean;    
    Code?: string;    
    Name?: string;    
    Display?: string;    
    Description?: string;    
    SortOrder?: number;       
    ImageFileName?: string;       
    ImageURL?: string;       
    Slug?: string;       
    URL?: string;       
    ContentOriginal?: string;       
    ContentHTML?: string;       
    UnitID?: number;       
    Weight?: number;       
    NameOriginal?: string;       
    Specifications?: string;       
    NameSpecial?: string;       
    CompanyID?: number;   
    UnitID02?: number;       
    Weight02?: number;        
    SpecificationsNumber?: number;      
    ParentName?: string;       
    CompanyName?: string;       
    QuantityExport?: number;      
    QuantityExport02?: number;      
    QuantityImport?: number;      
    QuantityImport02?: number;      
    QuantityInStock?: number;      
    QuantityInStock02?: number;      
}

